version: "3.8"

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - .:/app  # Optional: Mount your code directory inside the container for live reloads
